- name: Scan app for Kubernetes Secret usage and suggest improvements
  hosts: localhost
  gather_facts: false
  vars:
    namespace: "{{ namespace }}"
    deployment_name: "{{ deployment_name }}"
    ocp_api_host: "{{ ocp_api_host }}"
    ocp_token: "{{ ocp_token }}"
  tasks:
    - name: Get deployment spec
      kubernetes.core.k8s_info:
        kind: Deployment
        api_version: apps/v1        
        name: "{{ deployment_name }}"
        namespace: "{{ namespace }}"
        host: "https://{{ ocp_api_host }}"
        api_key: "{{ ocp_token }}"
        verify_ssl: false
      register: dep_info

    - name: Extract referenced secrets from deployment
      set_fact:
        used_secrets: "{{ dep_info.resources[0].spec.template.spec | community.general.json_query(secret_query) }}"
      vars:
        secret_query: "[containers[].env[].valueFrom.secretKeyRef.name, volumes[].secret.secretName]"

    - name: Flatten and clean up used secrets
      set_fact:
        used_secrets_flat: "{{ used_secrets | flatten | select('defined') | list | unique }}"

    - name: Get all secrets in namespace
      kubernetes.core.k8s_info:
        kind: Secret
        api_version: v1
        namespace: "{{ namespace }}"
        host: "https://{{ ocp_api_host }}"
        api_key: "{{ ocp_token }}"
        verify_ssl: false
      register: all_secrets

    - name: Show used vs available secrets
      debug:
        msg: |
          🔐 Deployment "{{ deployment_name }}" is using these Kubernetes secrets:
          {% for s in used_secrets_flat %}
          - {{ s }}
          {% endfor %}

          📦 Available Secrets in namespace "{{ namespace }}":
          {% for s in all_secrets.resources %}
          - {{ s.metadata.name }} (type: {{ s.type }})
          {% endfor %}

    - name: Suggest improvements
      debug:
        msg: |
          💡 Recommendations:
          {% for s in used_secrets_flat %}
          - Secret '{{ s }}' might be a candidate for CyberArk Conjur integration.
            Consider replacing static secret with dynamic retrieval using the Secrets Provider sidecar or init container.
          {% endfor %}
