- name: Scan app for Kubernetes Secret usage and suggest improvements
  hosts: localhost
  gather_facts: false
  vars:
    k8s_namespace: "{{ k8s_namespace }}"
    deployment_name: "{{ deployment_name }}"
    ocp_api_host: "{{ ocp_api_host }}"
    ocp_token: "{{ ocp_token }}"
  tasks:
    - name: Get deployment spec
      kubernetes.core.k8s_info:
        kind: Deployment
        api_version: apps/v1        
        name: "{{ deployment_name }}"
        namespace: "{{ k8s_namespace }}"
        host: "https://{{ ocp_api_host }}"
        api_key: "{{ ocp_token }}"
        verify_ssl: false
      register: dep_info

    - name: Fallback-safe extraction of secrets from deployment
      set_fact:
        used_secrets: >-
          {{
            (
              dep_info.resources[0].spec.template.spec.containers | map(attribute='env') | select('defined') | list | sum(start=[]) |
              map(attribute='valueFrom') | select('defined') |
              map(attribute='secretKeyRef') | select('defined') |
              map(attribute='name')
            )
            +
            (
              dep_info.resources[0].spec.template.spec.volumes | selectattr('secret.secretName', 'defined') |
              map(attribute='secret.secretName')
            )
          | list | unique }}

    - name: Get all secrets in namespace
      kubernetes.core.k8s_info:
        kind: Secret
        api_version: v1
        namespace: "{{ k8s_namespace }}"
        host: "https://{{ ocp_api_host }}"
        api_key: "{{ ocp_token }}"
        verify_ssl: false
      register: all_secrets

    - name: Show used vs available secrets
      debug:
        msg: |
          🔐 Deployment "{{ deployment_name }}" is using these Kubernetes secrets:
          {% for s in used_secrets %}
          - {{ s }}
          {% end
