- name: Scan app for Kubernetes Secret usage and authenticate to Conjur
  hosts: localhost
  gather_facts: false
  vars:
    policy_template_file: conjur_host_policy_template.j2
    policy_rendered_file: /tmp/conjur_app_path_policy.yaml
    variable_policy_template_file: conjur_variables_template.j2
    variable_policy_rendered_file: /tmp/conjur_generated_variables.yaml

  tasks:
    # Step 1: Fetch deployment details from OpenShift API
    - name: Get deployment spec
      kubernetes.core.k8s_info:
        kind: Deployment
        api_version: apps/v1
        name: "{{ deployment_name }}"
        namespace: "{{ k8s_namespace }}"
        host: "https://{{ ocp_api_host }}"
        api_key: "{{ ocp_token }}"
        verify_ssl: false
      register: dep_info

    - name: Debug if deployment exists
      debug:
        msg: "❌ No deployment found with name '{{ deployment_name }}' in namespace '{{ k8s_namespace }}'."
      when: dep_info.resources | length == 0

    # Step 2: Extract secret references from the deployment
    - name: Extract referenced secrets from deployment
      set_fact:
        used_secrets: >-
          {{
            (
              dep_info.resources[0].spec.template.spec.containers
              | map('default', {}) | select('defined') | list
              | map(attribute='env') | map('default', []) | list | sum(start=[])
              | map(attribute='valueFrom') | select('defined')
              | map(attribute='secretKeyRef') | select('defined')
              | map(attribute='name')
            )
            +
            (
              dep_info.resources[0].spec.template.spec.volumes
              | default([]) | selectattr('secret.secretName', 'defined')
              | map(attribute='secret.secretName')
            )
          | list | unique }}
      when: dep_info.resources | length > 0

    # Step 3: Retrieve all secrets in namespace
    - name: Get all secrets in namespace
      kubernetes.core.k8s_info:
        kind: Secret
        api_version: v1
        namespace: "{{ k8s_namespace }}"
        host: "https://{{ ocp_api_host }}"
        api_key: "{{ ocp_token }}"
        verify_ssl: false
      register: all_secrets

    - name: Extract keys from used secrets
      set_fact:
        secret_keys: >-
          {{ all_secrets.resources | selectattr('metadata.name', 'in', used_secrets)
                                   | map(attribute='data') | list
                                   | map('dict2items') | list | sum(start=[])
                                   | map(attribute='key') | list | unique }}

    # Step 4: Print secret improvement suggestions
    - name: Suggest improvements
      debug:
        msg: |
          💡 Recommendations:
          {% for s in used_secrets %}
          - Secret '{{ s }}' might be a candidate for CyberArk Conjur integration.
            Consider replacing static secret with dynamic retrieval using the Secrets Provider sidecar or init container.
          {% endfor %}

    # Step 5: Authenticate to Conjur (API key + session token)
    - name: Login to Conjur (get API key)
      shell: >
        curl -s -k --user {{ conjur_username }}:{{ conjur_password }}
        https://{{ conjur_host }}/authn/{{ conjur_account }}/login
      register: conjur_login_response
      no_log: true

    - name: Authenticate to Conjur (get session token)
      shell: >
        curl -s -k --data '{{ conjur_login_response.stdout }}'
        https://{{ conjur_host }}/authn/{{ conjur_account }}/{{ conjur_username }}/authenticate
      register: conjur_session_token_raw
      no_log: true

    - name: Base64 encode the session token
      shell: |
        echo '{{ conjur_session_token_raw.stdout }}' | base64 | tr -d '\n'
      register: conjur_session_token_b64
      no_log: true

    # Step 6: List Conjur resources (verify token)
    - name: Call Conjur API to list all resources (conjur list)
      shell: >
        curl -s -k -H "Authorization: Token token=\"{{ conjur_session_token_b64.stdout }}\""
        https://{{ conjur_host }}/resources/{{ conjur_account }}
      register: conjur_list_output

    - name: Parse and extract Conjur resource IDs
      set_fact:
        conjur_resources: "{{ conjur_list_output.stdout | from_json | map(attribute='id') | list }}"

    - name: Show full Conjur resource list (formatted line by line)
      debug:
        var: conjur_resources

    # Step 7: Render and load host identity policy
    - name: Render host policy from Jinja template
      template:
        src: "{{ policy_template_file }}"
        dest: "{{ policy_rendered_file }}"

    - name: Read rendered host policy file
      slurp:
        src: "{{ policy_rendered_file }}"
      register: policy_file_content

    - name: Load host policy into Conjur (POST)
      uri:
        url: "https://{{ conjur_host }}/policies/{{ conjur_account }}/policy/root"
        method: POST
        headers:
          Authorization: "Token token=\"{{ conjur_session_token_b64.stdout }}\""
          Content-Type: "application/x-yaml"
        body: "{{ policy_file_content['content'] | b64decode }}"
        body_format: raw
        validate_certs: false
      register: policy_load_response
      failed_when: policy_load_response.status not in [200, 201]
      ignore_errors: true

    # Step 8: Confirm host identity created
    - name: Check if new host was added
      set_fact:
        new_host_id: "app-path/system:serviceaccount:{{ k8s_namespace }}:{{ service_account }}"

    - name: Validate host creation
      debug:
        msg: "✅ Host '{{ new_host_id }}' was successfully registered in Conjur."
      when: new_host_id in conjur_resources | join(',')

    # Step 9: Generate variable & grant policy
    - name: Render Conjur variable+grant policy from template
      template:
        src: "{{ variable_policy_template_file }}"
        dest: "{{ variable_policy_rendered_file }}"

    - name: Read rendered variable policy file
      slurp:
        src: "{{ variable_policy_rendered_file }}"
      register: variable_policy_file_content

    - name: Load secrets variable & access policy
      uri:
        url: "https://{{ conjur_host }}/policies/{{ conjur_account }}/policy/root"
        method: POST
        headers:
          Authorization: "Token token=\"{{ conjur_session_token_b64.stdout }}\""
          Content-Type: "application/x-yaml"
        body: "{{ variable_policy_file_content['content'] | b64decode }}"
        body_format: raw
        validate_certs: false
      register: secret_policy_result

    # Step 10: Show status and CLI equivalent
    - name: Show policy load result (final status)
      debug:
        msg: >
          📝 Final policy load status:
          - Host policy POST: {{ policy_load_response.status | default('N/A') }}
          - Variable policy POST: {{ secret_policy_result.status | default('N/A') }}

    - name: CLI equivalent commands
      debug:
        msg: |
          💡 Equivalent CLI:
          conjur policy load -f {{ policy_rendered_file }} -b root
          conjur policy load -f {{ variable_policy_rendered_file }} -b root
